### ISSUE TITLE
including images in random walk notebooks

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/PHY494-resources#5]
Instead of using `display(filename)` you can use markdown code: put "image.png" in the same directory and then use
```md
![description of the image](image.png)
```

(If you copied the image from somewhere then add an attribution below the image, E.g. "Source: Author, URL")

**Comment by ChenouZhang** [comment]
Updated my notebooks. Used md instead of display for images.
